### ISSUE TITLE
[Fixed] [Modrinth and CF versions need to be upgraded] [1.19.2] Incompatible with Carpet MiniTweaks, both add gamerule to disable enderdragon griefing.

### ISSUE THREAD

**Issue by grimSagely** [MaheEvil/EndGrief#1]
The additional obsidian pillar / end crystal tweaks are pretty nice, not sure if worth making specific compat for.
https://github.com/manyrandomthings/minitweaks#minitweaks-carpet-rules-list

**Comment by AdelinaM17n** [comment]
Hey sorry I didn't notice this issue, I will take a look into this

**Comment by AdelinaM17n** [comment]
Fixed in the latest commit, will update later
